### ISSUE TITLE
SWEET Ontology Alignments

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/GSoC#5]
# Idea
The [Semantic Web for Earth and Environmental Terminology](https://github.com/ESIPFed/sweet) (SWEET) Ontology SWEET is a highly modular ontology suite with ~7000 concepts in 225 separate ontologies covering Earth system science. Under community development and governance at the ESIP [Semantic Technologies Committee](http://wiki.esipfed.org/index.php/Semantic_Technologies), there are a number of ongoing [ontology alignment](https://en.wikipedia.org/wiki/Ontology_alignment) activities for which a significant degree of work has still to be done. To this end we are looking to engage in addressing both [open issues](https://github.com/ESIPFed/sweet/issues) as well as new ontology alignments with other Semantic Web resources in a bid to grow the usefulness of SWEET as a primary earth system science knowledge resource.

# Skills Needed
XML, Turtle, Protege, Semantic Web

# Mentors
Lewis John McGibbney, NASA JPL

**Comment by malgamves** [comment]
I can't get good reading content on ontology alignment. Any other resources available?

**Comment by lewismc** [comment]
Hi @malgamves thanks for your interest sorry about lack of response. In short, yes, please see the [SWEET Alignment Manager](https://github.com/ESIPFed/sweet-tools/tree/master/sweet-alignment-manager). Also in terms of literature, you have a wealth of information available at the [ontology matching workshop](http://ontologymatching.org/) as well as [Ontology Matching 2017](http://om2017.ontologymatching.org/) which is held every year beside the International Semantic Web Conference.

**Comment by malgamves** [comment]
It's ok! @lewismc I'd like to take this issue on. Can I have your guidance?

**Comment by jaydeepchakraborty** [comment]
Hi lewismc, I know I am late but if possible can you please clarify the problem statements?
1) I have downloaded SWEET ontology from this "link https://sweet.jpl.nasa.gov/download" and I am using version "SWEET 2.3". Am I looking into correct ontology? 
Because in "SWEET Alignment Manager", under "alignments", there is entity "http://sweetontology.net/matrEquipment/Communication". Which I can not find in "SWEET 2.3", but I can find "http://sweet.jpl.nasa.gov/2.3/matrEquipment#Communication".


2) In "SWEET Alignment Manager", under "target" there are 
datasetontology.ttl
instruments.ttl
platforms.ttl (this is missing in "alignments", I guess because it only contains labels)
prov-o.ttl
sciencekeywords.ttl
sosa.ttl

Are these the targets we have to deal with the scope of the project?

3) Under "alignments" in some targets, the output has similar properties(object property, data property) and in some has similar concepts(class). Are these both(property alignment and concept alignment) come under the scope of the project?

4) You mentioned about "AML", in the project proposal. Is it mandatory that our proposal has to be aligned with "AML" or we can propose any other idea based on some recent papers?

5) Is there any way I can share the project proposal beforehand so that you can take a look and suggest to improve?

**Comment by lewismc** [comment]
@malgamves are you still interested in this? The documentation above provides all of the prerequisite reading resources.

**Comment by lewismc** [comment]
@jaydeepchakraborty 

> I have downloaded SWEET ontology from this "link https://sweet.jpl.nasa.gov/download" and I am using version "SWEET 2.3". Am I looking into correct ontology?

No, look at the above hyperlink for SWEET... it links to https://github.com/ESIPFed/sweet

> Are these the targets we have to deal with the scope of the project?

Some of them yes... there are several other ones as well, which again are documented above at https://github.com/ESIPFed/sweet/issues

**Comment by jaydeepchakraborty** [comment]
@lewismc , thank you for replying back.

I am writing a proposal for this project, is there any way I can share with you please?

**Comment by lewismc** [comment]
Yes @jaydeepchakraborty  please share with me a GDoc hyperlink. Thanks

**Comment by jaydeepchakraborty** [comment]
@lewismc  , I have one more question. Do you have any corpus of Earth and Environmental Terminology?

**Comment by lewismc** [comment]
@jaydeepchakraborty can you elaborate?

**Comment by malgamves** [comment]
Yes @lewismc I am still interested, I've added them to my reading list.. my proposal is in the works.

**Comment by jaydeepchakraborty** [comment]
@lewismc  Sorry for the confusion. I was looking for a corpus(documents) which has information about the concepts, properties, and instances of SWEET ontology(at least used those concepts, properties, and instances in documents) and same for target ontologies.

**Comment by lewismc** [comment]
@malgamves OK

**Comment by lewismc** [comment]
@jaydeepchakraborty in all honesty no... the concepts, properties, and instances contained within the SWEET ontology suite are derived from across the while of Earth and environmental terminology. 
As part of your proposal it would be nice for your select a number of alignment resources and then undertake the prerequisite literature review. This is the best information I can give you at this stage. There is no manual for this... we make it up as we go.

**Comment by Gautamshahi** [comment]
@lewismc I have an experience of working in the Ontology Development and Ontology Alignment. Looking forward to the discussion.

**Comment by lewismc** [comment]
Thanks @Gautamshahi

**Comment by graybeal** [comment]
Even if it's 'too late', here is information I thought worth including in the thread. There is a group, described below, that has been gathering information about reconciling parameter names, and has had quite a few webinars (recorded) of different teams presenting their own approaches to parameter names. I am watching the Pangaea presentation, it's quite interesting. These would form a great basis for investigating how and to what to map SWEET.

The Research Data Alliance (RDA, https://rd-alliance.org) Vocabulary and Semantic Services Interest Group (VSSIG, https://www.rd-alliance.org/groups/vocabulary-services-interest-group.html) has a working group called Harmonizing Measurement Parameters. These working groups don't necessarily have home pages, but you can see more in column AB of https://docs.google.com/spreadsheets/d/1gQ5FK7LXmdE5VdXMnDBP8uSJ3Ca-B5MqArro1yWI7K8/edit#gid=0), and see more about how to sign up at the Document Overview at 
https://docs.google.com/spreadsheets/d/1gQ5FK7LXmdE5VdXMnDBP8uSJ3Ca-B5MqArro1yWI7K8/edit#gid=837330156.
